-- MAGASIN NOIBO — GitHub ↔ Supabase integration test
-- This migration is intentionally harmless and temporary.
-- It creates a marker table so we can verify that a commit on GitHub
-- is automatically applied to the Supabase production database.

create table if not exists public._github_supabase_integration_test (
  id bigint generated by default as identity primary key,
  marker text not null,
  created_at timestamptz not null default now()
);

insert into public._github_supabase_integration_test (marker)
values ('GITHUB_SUPABASE_AUTO_DEPLOY_OK');
