/* MAGASIN — Employee V40 attendance bridge.
 * Keeps the existing V40 attendance form intact.
 * Adds manual completion + automatic attendance from APPROVED schedules.
 */
(function(window,document){
'use strict';
const SUPABASE_URL='https://menvbzlsncmpuvnaifxa.supabase.co';
const SUPABASE_KEY='sb_publishable_HsvCS6HDZnCDInd9PUoh0g_V34wJVqx';
const TZ='Asia/Ho_Chi_Minh';
let client=null,templateHtml='',captured=false,restoring=false;
function getClient(){if(client)return client;if(!window.supabase?.createClient)return null;client=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{autoRefreshToken:true,persistSession:true,detectSessionInUrl:true}});return client;}
function pad(n){return String(n).padStart(2,'0');}
function parts(){const a=new Intl.DateTimeFormat('en-CA',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()),o={};a.forEach(x=>o[x.type]=x.value);return {y:+o.year,m:+o.month,d:+o.day};}
function key(y,m,d){return `${y}-${pad(m)}-${pad(d)}`;}
function lastDay(y,m){return new Date(Date.UTC(y,m,0)).getUTCDate();}
function fmt(v){if(!v)return '';const p=String(v).split('-');return p.length===3?`${p[2]}/${p[1]}/${p[0]}`:String(v);}
function time5(v){return v?String(v).slice(0,5):'';}
function periods(){const t=parts(),ms=key(t.y,t.m,1);if(t.d<=15){const d=new Date(Date.UTC(t.y,t.m-2,1));return {cs:ms,ce:key(t.y,t.m,15),ps:key(d.getUTCFullYear(),d.getUTCMonth()+1,16),pe:key(t.y,t.m,0),to:key(t.y,t.m,t.d)};}return {cs:key(t.y,t.m,16),ce:key(t.y,t.m,lastDay(t.y,t.m)),ps:ms,pe:key(t.y,t.m,15),to:key(t.y,t.m,t.d)};}
function panel(){return document.querySelector('#view-attendance .attendance-entry-grid .panel:first-child');}
function statusBox(p){let e=p?.querySelector('#attendanceAutoStatus');if(!e&&p){e=document.createElement('div');e.id='attendanceAutoStatus';e.style.cssText='margin-top:10px;padding:10px 12px;border-radius:10px;background:#eef7ff;color:#235dba;border:1px solid #d9e8f7;font-size:12px;line-height:1.45';p.appendChild(e);}return e;}
function fields(p){const date=p?.querySelector('input[type="date"]');const ss=[...(p?.querySelectorAll('select')||[])];const store=ss.find(s=>[...s.options].some(o=>/^CN\d+/i.test(String(o.value||o.textContent||'').trim())))||ss[0]||null;const ts=ss.filter(s=>s!==store);return {date,store,start:ts[0]||null,end:ts[1]||null};}
async function refreshHistory(){const table=document.getElementById('attendanceHistoryTable'),c=getClient();if(!table||!c)return;const from=document.getElementById('attendanceFrom')?.value||null,to=document.getElementById('attendanceTo')?.value||null;const {data,error}=await c.rpc('get_my_attendance_v2',{p_from_date:from,p_to_date:to});if(error)return;const rows=Array.isArray(data)?data:[],body=table.querySelector('tbody');if(!body)return;body.innerHTML=rows.map(r=>`<tr><td>${fmt(r.work_date)}</td><td>${r.store_code||r.store_name||''}</td><td>${time5(r.check_in_time||r.check_in)}</td><td>${time5(r.check_out_time||r.check_out)}</td><td>${Number(r.hours_worked||0).toFixed(1)}</td><td>${Number(r.amount||0).toLocaleString('vi-VN')}đ</td></tr>`).join('');}
async function manual(){const p=panel();if(!p)return;const f=fields(p),d=f.date?.value||'',store=f.store?.value||f.store?.selectedOptions?.[0]?.textContent?.trim()||'',start=f.start?.value||'',end=f.end?.value||'',st=statusBox(p);if(!d||!store||!start||!end){st.textContent='Vui lòng nhập đủ ngày, cửa hàng, giờ vào và giờ ra.';st.style.color='#9d3f30';return;}if(end<=start){st.textContent='Giờ ra phải sau giờ vào.';st.style.color='#9d3f30';return;}if(!window.confirm(`Hoàn thành chấm công?\n\nNgày: ${fmt(d)}\nCửa hàng: ${store}\nGiờ: ${start}–${end}\n\nHệ thống chỉ chấm theo ca APPROVED tương ứng và không cho chấm ca chưa kết thúc.`))return;const c=getClient();if(!c){st.textContent='Không thể kết nối Supabase.';st.style.color='#9d3f30';return;}const btn=p.querySelector('[data-manual-attendance="1"]');if(btn)btn.disabled=true;st.textContent='Đang đối chiếu lịch chính thức…';st.style.color='#235dba';try{const {error}=await c.rpc('manual_attendance_from_schedule',{p_work_date:d,p_store_code:store,p_check_in:start,p_check_out:end});if(error)throw error;st.textContent='Đã hoàn thành chấm công thành công.';await refreshHistory();}catch(e){const m=String(e?.message||e),map={APPROVED_SCHEDULE_NOT_FOUND:'Không tìm thấy ca APPROVED trùng với thông tin đã nhập.',SCHEDULE_ALREADY_ATTENDED:'Ca này đã được chấm công trước đó, hệ thống không tạo trùng.',SHIFT_NOT_FINISHED:'Ca hôm nay chưa kết thúc nên chưa thể hoàn thành chấm công.',SCHEDULE_IN_FUTURE:'Không thể chấm công cho ngày tương lai.'};st.textContent=map[m]||`Chấm công thất bại: ${m}`;st.style.color='#9d3f30';}finally{if(btn)btn.disabled=false;}}
async function autoRun(){const p=panel(),b=document.getElementById('attendanceAutoButton');if(!p||!b)return;const q=periods(),st=statusBox(p);if(!window.confirm(`Tự động chấm công theo kỳ lương:\n• Kỳ hiện tại: ${fmt(q.cs)} – ${fmt(q.ce)}\n• Kỳ trước: ${fmt(q.ps)} – ${fmt(q.pe)}\n• Chỉ đến thời điểm thực tế tại Việt Nam: ${fmt(q.to)}\n\nChỉ chấm ca APPROVED đã kết thúc. Ca đã chấm sẽ bỏ qua. Không chấm ca tương lai.\n\nTiếp tục?`))return;const c=getClient();if(!c){st.textContent='Không thể kết nối Supabase.';st.style.color='#9d3f30';return;}b.disabled=true;st.textContent='Đang đối chiếu 2 kỳ lương và thời điểm thực tế…';st.style.color='#235dba';try{const {data,error}=await c.rpc('auto_attendance_from_approved_schedules',{p_from_date:null,p_to_date:null});if(error)throw error;const rows=Array.isArray(data)?data:[],a=rows.filter(r=>r.action==='AUTO_COMPLETED').length,s=rows.filter(r=>r.action==='SKIPPED_ALREADY_ATTENDED').length;st.textContent=rows.length?`Đã tự động chấm ${a} ca; bỏ qua ${s} ca đã có chấm công.`:'Không có ca APPROVED đã kết thúc cần tự động chấm.';await refreshHistory();}catch(e){st.textContent=`Tự động chấm công thất bại: ${e?.message||e}`;st.style.color='#9d3f30';}finally{b.disabled=false;}}
function bind(p){if(!p)return false;let done=[...p.querySelectorAll('button')].find(b=>b.textContent.trim()==='Hoàn thành chấm công');if(!done)return false;if(done.dataset.manualAttendance!=='1'){const c=done.cloneNode(true);c.type='button';c.dataset.manualAttendance='1';done.replaceWith(c);done=c;c.addEventListener('click',manual);}let auto=document.getElementById('attendanceAutoButton');if(!auto){auto=document.createElement('button');auto.type='button';auto.id='attendanceAutoButton';auto.className='btn secondary';auto.textContent='Tự động chấm công';auto.style.marginLeft='8px';auto.title='Tự động chấm kỳ hiện tại và kỳ trước; bỏ qua ca đã chấm.';done.insertAdjacentElement('afterend',auto);auto.addEventListener('click',autoRun);}else if(!auto.dataset.bound){auto.dataset.bound='1';auto.onclick=autoRun;}return true;}
function captureAndProtect(){const p=panel();if(!p)return false;if(!captured){templateHtml=p.innerHTML;captured=true;}if(restoring)return true;if(p.innerHTML!==templateHtml){restoring=true;p.innerHTML=templateHtml;restoring=false;}bind(p);return true;}
function boot(){captureAndProtect();new MutationObserver(captureAndProtect).observe(document.documentElement,{childList:true,subtree:true,characterData:true});setInterval(captureAndProtect,500);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})(window,document);
