/* MAGASIN — Official Lịch làm module V2
 * Employee: list_my_approved_schedules_v2
 * Manager/Owner: get_manager_weekly_schedule
 * Manager schedule click is read-only.
 */
(function(){
  'use strict';
  const sb=window.MAGASIN_SUPABASE;if(!sb)return;
  let offset=0,storeFilter='all',rows=[],stores=[],installed=false;
  const DAYS=['Thứ Hai','Thứ Ba','Thứ Tư','Thứ Năm','Thứ Sáu','Thứ Bảy','Chủ Nhật'];
  const $=id=>document.getElementById(id);
  const esc=v=>String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
  const isManager=()=>['OWNER','STORE_MANAGER'].includes(String(window.MAGASIN_PROFILE?.role||'STAFF').toUpperCase());
  function monday(d=new Date()){const x=new Date(d);x.setHours(12,0,0,0);const day=x.getDay();x.setDate(x.getDate()-(day===0?6:day-1));return x}
  const add=(d,n)=>{const x=new Date(d);x.setDate(x.getDate()+n);return x};
  const key=d=>d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');
  const fmt=d=>new Intl.DateTimeFormat('vi-VN',{day:'2-digit',month:'2-digit'}).format(d);
  const label=()=>{const a=add(monday(),offset*7),b=add(a,6);return `Tuần ${fmt(a)}–${fmt(b)}`};
  const color=t=>String(t||'').startsWith('12:')?'red':(String(t||'').startsWith('14:')||String(t||'').startsWith('17:')?'cyan':'yellow');
  function css(){if($('msv2-css'))return;const s=document.createElement('style');s.id='msv2-css';s.textContent=`
.ms2-head{display:flex;justify-content:space-between;gap:14px;align-items:flex-start;flex-wrap:wrap}.ms2-controls{display:flex;gap:8px;flex-wrap:wrap}.ms2-controls select{min-width:160px}.ms2-hero{padding:18px 20px;margin-top:16px}.ms2-week{font-size:18px;font-weight:800}.ms2-cal{padding:14px;margin-top:16px}.ms2-grid{display:grid;grid-template-columns:repeat(7,minmax(190px,1fr));gap:10px;overflow:auto}.ms2-day{min-width:190px;border:1px solid #e4eaf1;border-radius:14px;overflow:hidden;background:#fff}.ms2-dh{padding:11px;background:#f8fafd;border-bottom:1px solid #eef2f6}.ms2-dh strong,.ms2-dh span{display:block}.ms2-dh span{font-size:11px;color:#74839a;margin-top:3px}.ms2-body{padding:4px}.ms2-shift{display:block;width:calc(100% - 12px);margin:7px 6px;padding:10px;border:1px solid;border-radius:10px;text-align:left;cursor:pointer;font:500 11px Inter;background:#fff}.ms2-shift b,.ms2-shift span,.ms2-shift em{display:block}.ms2-shift b{font-size:12px}.ms2-shift span{margin-top:4px;font-weight:700}.ms2-shift em{margin-top:3px;font-size:10px;font-style:normal;opacity:.9}.ms2-shift.yellow{background:#fff9d8;border-color:#f0e6a3;color:#725f00}.ms2-shift.red{background:#fbe4e4;border-color:#edbaba;color:#9a3838}.ms2-shift.cyan{background:#ddf8f8;border-color:#a3dfdf;color:#08777a}.ms2-empty{padding:24px 8px;text-align:center;color:#95a3b7;font-size:11px}.ms2-legend{display:flex;gap:14px;flex-wrap:wrap;color:#74839a;font-size:11px;margin-top:14px}.ms2-dot{display:inline-block;width:10px;height:10px;border-radius:50%;margin-right:5px}.ms2-dot.y{background:#eadb60}.ms2-dot.r{background:#e9a5a5}.ms2-dot.c{background:#7dd7d7}#ms2-detail{position:fixed;inset:0;display:none;align-items:center;justify-content:center;padding:20px;background:rgba(15,35,55,.38);z-index:2147483647}#ms2-detail.open{display:flex}.ms2-modal{width:min(470px,calc(100vw - 40px));background:#fff;border:1px solid #e4eaf1;border-radius:18px;box-shadow:0 18px 50px rgba(16,42,67,.22);padding:22px}.ms2-details{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:16px}.ms2-detail{padding:12px;background:#fbfcfe;border:1px solid #edf1f5;border-radius:10px}.ms2-detail span{display:block;color:#74839a;font-size:10px}.ms2-detail strong{display:block;margin-top:4px;font-size:13px}.ms2-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:18px}@media(max-width:600px){.ms2-details{grid-template-columns:1fr}}
`;document.head.appendChild(s)}
  function modal(){if($('ms2-detail'))return;const d=document.createElement('div');d.id='ms2-detail';d.innerHTML=`<div class="ms2-modal" role="dialog" aria-modal="true"><div class="ms2-head"><div><h2 id="ms2-name" style="margin:0">—</h2><div class="muted">Chi tiết ca chính thức · chỉ xem</div></div><button class="btn ghost" id="ms2-close">×</button></div><div class="ms2-details"><div class="ms2-detail"><span>NGÀY</span><strong id="ms2-date">—</strong></div><div class="ms2-detail"><span>GIỜ LÀM</span><strong id="ms2-time">—</strong></div><div class="ms2-detail"><span>CHI NHÁNH</span><strong id="ms2-store">—</strong></div><div class="ms2-detail"><span>TRẠNG THÁI</span><strong>Đã phát hành</strong></div></div><div class="ms2-actions"><button class="btn primary" id="ms2-attendance">Xem chấm công</button><button class="btn ghost" id="ms2-close2">Đóng</button></div></div>`;document.body.appendChild(d);$('ms2-close').onclick=close;$('ms2-close2').onclick=close;$('ms2-attendance').onclick=()=>{close();document.querySelector('[data-page="attendance"]')?.click()};d.onclick=e=>{if(e.target===d)close()};}
  function close(){const d=$('ms2-detail');if(d){d.classList.remove('open');document.body.style.overflow='';}}
  function open(r){if(!r)return;modal();$('ms2-name').textContent=r.employee_name||window.MAGASIN_PROFILE?.full_name||'Nhân viên';$('ms2-date').textContent=r.work_date;$('ms2-time').textContent=String(r.start_time).slice(0,5)+'–'+String(r.end_time).slice(0,5);$('ms2-store').textContent=r.store_name||r.store_code||'—';$('ms2-detail').classList.add('open');document.body.style.overflow='hidden';}
  async function loadStores(){if(!isManager()){stores=[];return}const {data,error}=await sb.from('stores').select('id,code,name').eq('status','ACTIVE').order('code');if(error)throw error;stores=data||[]}
  async function load(){const ws=key(add(monday(),offset*7));if(isManager()){const sid=storeFilter==='all'?null:stores.find(s=>s.code===storeFilter)?.id||null;const {data,error}=await sb.rpc('get_manager_weekly_schedule',{p_store_id:sid,p_week_start:ws});if(error)throw error;rows=data||[];}else{const {data,error}=await sb.rpc('list_my_approved_schedules_v2',{p_week_start:ws});if(error)throw error;rows=data||[];}render();}
  function render(){const c=$('content');if(!c)return;const base=monday(),filter=isManager()?`<select id="ms2-store"><option value="all">Tất cả cửa hàng</option>${stores.map(s=>`<option value="${esc(s.code)}"${s.code===storeFilter?' selected':''}>${esc(s.code)} · ${esc(s.name)}</option>`).join('')}</select>`:'';c.innerHTML=`<section class="card panel"><div class="ms2-head"><div><h2>Lịch làm</h2><p>Lịch chính thức đã phát hành · Chỉ xem</p></div><div class="ms2-controls">${filter}<button class="btn ghost" id="ms2-prev">← Tuần trước</button><button class="btn ghost" id="ms2-today">Tuần này</button><button class="btn ghost" id="ms2-next">Tuần sau →</button></div></div><div class="card ms2-hero"><div class="row"><div><div class="ms2-week">${label()}</div><div class="muted" style="margin-top:4px">Thứ Hai → Chủ Nhật · Lịch chính thức</div></div><span class="badge green">ĐÃ PHÁT HÀNH</span></div></div><div class="card ms2-cal"><div class="ms2-grid">${DAYS.map((d,i)=>{const arr=rows.filter(r=>String(r.work_date).slice(0,10)===key(add(base,i)));return `<article class="ms2-day"><div class="ms2-dh"><strong>${d}</strong><span>${fmt(add(base,i))}</span></div><div class="ms2-body">${arr.length?arr.map(r=>`<button class="ms2-shift ${color(r.start_time)}" type="button" data-sid="${esc(r.schedule_id)}"><b>${esc(String(r.start_time).slice(0,5))}–${esc(String(r.end_time).slice(0,5))}</b><span>${esc(r.employee_name||window.MAGASIN_PROFILE?.full_name||'')}</span><em>${esc(r.store_name||r.store_code||'')}</em></button>`).join(''):'<div class="ms2-empty">Không có ca</div>'}</div></article>`}).join('')}</div><div class="ms2-legend"><span><i class="ms2-dot y"></i>06:00–14:00</span><span><i class="ms2-dot r"></i>12:00–17:00</span><span><i class="ms2-dot c"></i>14:00–22:00</span><span>Nhấp ca để xem chi tiết</span></div></div></section>`;c.querySelectorAll('.ms2-shift').forEach(b=>b.onclick=()=>open(rows.find(r=>String(r.schedule_id)===String(b.dataset.sid))));$('ms2-store')?.addEventListener('change',e=>{storeFilter=e.target.value;load().catch(showError)});$('ms2-prev')?.addEventListener('click',()=>{offset--;load().catch(showError)});$('ms2-today')?.addEventListener('click',()=>{offset=0;load().catch(showError)});$('ms2-next')?.addEventListener('click',()=>{offset++;load().catch(showError)});}
  function showError(e){const c=$('content');if(c)c.innerHTML=`<section class="card panel"><h2>Lịch làm</h2><div class="error-box">${esc(e?.message||'Không thể tải lịch.')}</div></section>`}
  async function activate(){if(!window.MAGASIN_PROFILE)return;css();modal();await loadStores();await load().catch(showError)}
  function boot(){if(installed)return;installed=true;document.addEventListener('click',e=>{if(e.target.closest('[data-page="schedule"]'))setTimeout(()=>activate(),80)});const c=$('content');if(c)new MutationObserver(()=>{if(document.querySelector('[data-page="schedule"].active'))setTimeout(()=>activate(),30)}).observe(c,{childList:true,subtree:true})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
