/* MAGASIN — Official Lịch làm module
 * Integrates the locked schedule contract into the existing web shell.
 * Employee: list_my_approved_schedules_v2
 * Manager/Owner: get_manager_weekly_schedule
 * Manager shift click is read-only.
 */
(function(){
  'use strict';
  const sb=window.MAGASIN_SUPABASE;
  if(!sb) return;
  let installed=false,offset=0,storeFilter='all',rows=[],stores=[];
  const DAYS=['Thứ Hai','Thứ Ba','Thứ Tư','Thứ Năm','Thứ Sáu','Thứ Bảy','Chủ Nhật'];
  const $=id=>document.getElementById(id);
  const esc=v=>String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
  function role(){return String(window.MAGASIN_PROFILE?.role||'STAFF').toUpperCase()}
  function manager(){return ['OWNER','STORE_MANAGER'].includes(role())}
  function monday(d=new Date()){const x=new Date(d);x.setHours(12,0,0,0);const day=x.getDay();x.setDate(x.getDate()-(day===0?6:day-1));return x}
  function addDays(d,n){const x=new Date(d);x.setDate(x.getDate()+n);return x}
  function key(d){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
  function fmt(d){return new Intl.DateTimeFormat('vi-VN',{day:'2-digit',month:'2-digit'}).format(d)}
  function weekLabel(){const a=addDays(monday(),offset*7),b=addDays(a,6);return `Tuần ${fmt(a)}–${fmt(b)}`}
  function color(t){const s=String(t||'');if(s.startsWith('12:'))return 'red';if(s.startsWith('14:')||s.startsWith('17:'))return 'cyan';return 'yellow'}
  function setupCss(){if($('magasin-schedule-ui-css'))return;const s=document.createElement('style');s.id='magasin-schedule-ui-css';s.textContent=`
.ms-head{display:flex;justify-content:space-between;align-items:flex-start;gap:14px;flex-wrap:wrap}.ms-controls{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.ms-controls select{min-width:160px}.ms-hero{margin-top:16px;padding:18px 20px}.ms-week{font-size:18px;font-weight:800}.ms-calendar{margin-top:16px;padding:14px}.ms-grid{display:grid;grid-template-columns:repeat(7,minmax(190px,1fr));gap:10px;overflow:auto}.ms-day{min-width:190px;border:1px solid #e4eaf1;border-radius:14px;overflow:hidden;background:#fff}.ms-day-head{padding:11px;background:#f8fafd;border-bottom:1px solid #eef2f6}.ms-day-head strong,.ms-day-head span{display:block}.ms-day-head span{margin-top:3px;color:#74839a;font-size:11px}.ms-day-body{padding:4px}.ms-shift{display:block;width:calc(100% - 12px);margin:7px 6px;padding:10px;border:1px solid;border-radius:10px;text-align:left;cursor:pointer;font:500 11px Inter;background:#fff}.ms-shift b,.ms-shift span,.ms-shift em{display:block}.ms-shift b{font-size:12px}.ms-shift span{margin-top:4px;font-weight:700}.ms-shift em{margin-top:3px;font-size:10px;font-style:normal;opacity:.9}.ms-shift.yellow{background:#fff9d8;border-color:#f0e6a3;color:#725f00}.ms-shift.red{background:#fbe4e4;border-color:#edbaba;color:#9a3838}.ms-shift.cyan{background:#ddf8f8;border-color:#a3dfdf;color:#08777a}.ms-shift.support{box-shadow:inset 3px 0 0 rgba(47,111,222,.7)}.ms-empty{padding:24px 8px;text-align:center;color:#95a3b7;font-size:11px}.ms-legend{display:flex;gap:14px;flex-wrap:wrap;color:#74839a;font-size:11px;margin-top:14px}.ms-dot{display:inline-block;width:10px;height:10px;border-radius:50%;margin-right:5px}.ms-dot.y{background:#eadb60}.ms-dot.r{background:#e9a5a5}.ms-dot.c{background:#7dd7d7}#msDetailOverlay{position:fixed;inset:0;display:none;align-items:center;justify-content:center;padding:20px;background:rgba(15,35,55,.38);z-index:2147483647}#msDetailOverlay.open{display:flex}#msDetailOverlay .ms-modal{width:min(470px,calc(100vw - 40px));background:#fff;border:1px solid #e4eaf1;border-radius:18px;box-shadow:0 18px 50px rgba(16,42,67,.22);padding:22px}.ms-detail-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:16px}.ms-detail{padding:12px;background:#fbfcfe;border:1px solid #edf1f5;border-radius:10px}.ms-detail span{display:block;color:#74839a;font-size:10px}.ms-detail strong{display:block;margin-top:4px;font-size:13px}.ms-detail-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:18px}@media(max-width:600px){.ms-detail-grid{grid-template-columns:1fr}}`;document.head.appendChild(s)}
  function ensureModal(){if($('msDetailOverlay'))return;const d=document.createElement('div');d.id='msDetailOverlay';d.innerHTML=`<div class="ms-modal" role="dialog" aria-modal="true"><div class="ms-head"><div><h2 id="msName" style="margin:0">—</h2><div class="muted">Chi tiết ca chính thức · chỉ xem</div></div><button class="btn ghost" id="msClose">×</button></div><div class="ms-detail-grid"><div class="ms-detail"><span>NGÀY</span><strong id="msDate">—</strong></div><div class="ms-detail"><span>GIỜ LÀM</span><strong id="msTime">—</strong></div><div class="ms-detail"><span>CHI NHÁNH</span><strong id="msStore">—</strong></div><div class="ms-detail"><span>TRẠNG THÁI</span><strong>Đã phát hành</strong></div></div><div class="ms-detail-actions"><button class="btn primary" id="msAttendance">Xem chấm công</button><button class="btn ghost" id="msClose2">Đóng</button></div></div>`;document.body.appendChild(d);$('msClose').onclick=closeModal;$('msClose2').onclick=closeModal;$('msAttendance').onclick=()=>{closeModal();document.querySelector('[data-page="attendance"]')?.click()};d.addEventListener('click',e=>{if(e.target===d)closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()})}
  function closeModal(){const d=$('msDetailOverlay');if(d){d.classList.remove('open');d.setAttribute('aria-hidden','true');document.body.style.overflow=''}}
  function openModal(r){ensureModal();$('msName').textContent=r.employee_name||window.MAGASIN_PROFILE?.full_name||'Nhân viên';$('msDate').textContent=r.work_date;$('msTime').textContent=String(r.start_time).slice(0,5)+'–'+String(r.end_time).slice(0,5);$('msStore').textContent=r.store_name||r.store_code||'—';const d=$('msDetailOverlay');d.classList.add('open');d.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
  async function loadStores(){const {data,error}=await sb.from('stores').select('id,code,name').eq('status','ACTIVE').order('code');if(error)throw error;stores=data||[]}
  async function loadRows(){const start=key(monday(addDays(new Date(),offset*7)));if(manager()){const {data,error}=await sb.rpc('get_manager_weekly_schedule',{p_store_id:storeFilter==='all'?null:(stores.find(s=>s.code===storeFilter)?.id||null),p_week_start:start});if(error)throw error;rows=data||[]}else{const {data,error}=await sb.rpc('list_my_approved_schedules_v2',{p_week_start:start});if(error)throw error;rows=data||[]}}
  function render(){const c=$('content');if(!c)return;const map=new Map(rows.map(r=>[String(r.schedule_id),r])),base=monday(addDays(new Date(),offset*7));const filterUi=manager()?`<select id="msStoreFilter"><option value="all">Tất cả cửa hàng</option>${stores.map(s=>`<option value="${esc(s.code)}" ${s.code===storeFilter?'selected':''}>${esc(s.code)} · ${esc(s.name)}</option>`).join('')}</select>`:'';c.innerHTML=`<section class="card panel"><div class="ms-head"><div><h2>Lịch làm</h2><p>Lịch chính thức đã được phát hành · Chỉ xem</p></div><div class="ms-controls">${filterUi}<button class="btn ghost" id="msPrev">← Tuần trước</button><button class="btn ghost" id="msToday">Tuần này</button><button class="btn ghost" id="msNext">Tuần sau →</button></div></div><div class="card ms-hero"><div class="row"><div><div class="ms-week">${weekLabel()}</div><div class="muted" style="margin-top:4px">Thứ Hai → Chủ Nhật · Lịch chính thức</div></div><span class="badge green">ĐÃ PHÁT HÀNH</span></div></div><div class="card ms-calendar"><div class="ms-grid">${DAYS.map((day,i)=>{const d=addDays(base,i),k=key(d),arr=rows.filter(r=>String(r.work_date).slice(0,10)===k);return `<article class="ms-day"><div class="ms-day-head"><strong>${day}</strong><span>${fmt(d)}</span></div><div class="ms-day-body">${arr.length?arr.map(r=>{const cc=color(r.start_time);return `<button type="button" class="ms-shift ${cc}" data-sid="${esc(r.schedule_id)}"><b>${esc(String(r.start_time).slice(0,5))}–${esc(String(r.end_time).slice(0,5))}</b><span>${esc(r.employee_name||window.MAGASIN_PROFILE?.full_name||'')}</span><em>${esc(r.store_name||r.store_code||'')}</em></button>`}).join(''):'<div class="ms-empty">Không có ca</div>'}</div></article>`}).join('')}</div><div class="ms-legend"><span><i class="ms-dot y"></i>06:00–14:00</span><span><i class="ms-dot r"></i>12:00–17:00</span><span><i class="ms-dot c"></i>14:00–22:00</span><span>Nhấp ca để xem chi tiết</span></div></div></section>`;c.querySelectorAll('.ms-shift').forEach(b=>b.onclick=()=>openModal(map.get(String(b.dataset.sid))||rows.find(r=>String(r.schedule_id)===String(b.dataset.sid))));$('msStoreFilter')?.addEventListener('change',e=>{storeFilter=e.target.value;load().catch(showError)});$('msPrev')?.addEventListener('click',()=>{offset--;load().catch(showError)});$('msToday')?.addEventListener('click',()=>{offset=0;load().catch(showError)});$('msNext')?.addEventListener('click',()=>{offset++;load().catch(showError)})}
  function showError(err){const c=$('content');if(c)c.innerHTML=`<section class="card panel"><h2>Lịch làm</h2><div class="error-box">${esc(err?.message||'Không thể tải lịch.')}</div></section>`}
  async function load(){await loadRows();render()}
  async function activate(){if(!window.MAGASIN_PROFILE)return;setupCss();ensureModal();await loadStores();await load()}
  function boot(){if(installed)return;installed=true;document.addEventListener('click',e=>{if(e.target.closest('[data-page="schedule"]'))setTimeout(()=>activate().catch(showError),120)});const target=$('content');if(target){const obs=new MutationObserver(()=>{if(document.querySelector('[data-page="schedule"].active'))setTimeout(()=>activate().catch(showError),40)});obs.observe(target,{childList:true,subtree:true})}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
