/* MAGASIN — Employee Workforce V2 UI */
(function(window, document){
'use strict';
const sb=window.MAGASIN_SUPABASE;if(!sb)return;
const $=id=>document.getElementById(id);const esc=v=>String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
const DAYS=['Thứ Hai','Thứ Ba','Thứ Tư','Thứ Năm','Thứ Sáu','Thứ Bảy','Chủ Nhật'];
const TYPES={AVAILABLE:'Có thể làm',PREFERRED:'Ưu tiên',UNAVAILABLE:'Không thể làm'};
let enabled=false,week=monday(businessToday()),availability=[],schedules=[],stores=[],profileRole='STAFF';
function businessToday(){const parts=new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Ho_Chi_Minh',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const y=Number(parts.find(x=>x.type==='year').value),m=Number(parts.find(x=>x.type==='month').value),d=Number(parts.find(x=>x.type==='day').value);return new Date(y,m-1,d,12,0,0);}
function monday(d){const x=new Date(d);x.setHours(12,0,0,0);const n=x.getDay();x.setDate(x.getDate()-(n===0?6:n-1));return x;}
function add(d,n){const x=new Date(d);x.setDate(x.getDate()+n);return x;}
function key(d){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');}
function fmt(d){return new Intl.DateTimeFormat('vi-VN',{day:'2-digit',month:'2-digit'}).format(d);}
function mins(v){const [h,m]=String(v).slice(0,5).split(':').map(Number);return h*60+m;}
function timeOpts(selected){let h='<option value="">Chọn giờ</option>';for(let i=0;i<24;i++)for(const m of [0,30]){const v=String(i).padStart(2,'0')+':'+String(m).padStart(2,'0');h+=`<option value="${v}" ${v===selected?'selected':''}>${v}</option>`;}return h;}
function storeOpts(selected){let h='<option value="">Không ưu tiên cửa hàng</option>';for(const s of stores)h+=`<option value="${esc(s.id)}" ${String(s.id)===String(selected??'')?'selected':''}>${esc(s.name||s.code)}</option>`;return h;}
function styles(){if($('wf-v2-styles'))return;const s=document.createElement('style');s.id='wf-v2-styles';s.textContent=`.wf-shell{display:grid;gap:16px}.wf-toolbar{display:flex;justify-content:space-between;align-items:center;gap:12px;flex-wrap:wrap}.wf-toolbar-group{display:flex;gap:8px;flex-wrap:wrap}.wf-btn{height:40px;padding:0 13px;border:1px solid #d9e2ec;border-radius:10px;background:#fff;color:#17243a;font-weight:700;cursor:pointer}.wf-btn.primary{border:0;background:linear-gradient(90deg,#16c3c5,#10b7d5);color:#fff}.wf-week-title{font-weight:800;font-size:18px}.wf-muted,.wf-note{font-size:12px;color:#74839a}.wf-status{min-height:20px;font-size:12px}.wf-error{padding:12px;border-radius:12px;background:#fff4f1;color:#9d3f30;border:1px solid #f2c8c0;font-size:13px}.wf-grid{display:grid;grid-template-columns:repeat(7,minmax(220px,1fr));gap:10px;overflow:auto}.wf-day{border:1px solid #dfe6ee;border-radius:15px;background:#fff;min-height:280px;overflow:hidden}.wf-day-head{padding:12px;border-bottom:1px solid #edf1f5;background:#fbfcfe}.wf-day-head strong,.wf-day-head span{display:block}.wf-day-head span{font-size:11px;color:#74839a;margin-top:3px}.wf-block{padding:10px;border-bottom:1px solid #edf1f5}.wf-block:last-child{border-bottom:0}.wf-block-title{display:flex;justify-content:space-between;font-size:12px;font-weight:800}.wf-list{display:grid;gap:7px;margin-top:8px}.wf-shift,.wf-item{padding:9px;border:1px solid #d8e1ea;border-radius:10px;margin-top:7px;background:#f9fbfd}.wf-shift b,.wf-item strong{display:block;font-size:11px}.wf-shift small,.wf-item span{display:block;margin-top:3px;color:#63738b;font-size:10px}.wf-item{display:flex;justify-content:space-between;gap:8px;align-items:center;margin-top:0}.wf-mini{height:30px;padding:0 9px;border:1px solid #d8e1ea;background:#fff;border-radius:8px;font-size:11px;font-weight:700;cursor:pointer}.wf-empty{padding:10px;color:#95a3b7;font-size:11px;text-align:center}.wf-editor{margin-top:8px;display:grid;gap:7px}.wf-editor-row{display:grid;grid-template-columns:1fr 1fr;gap:7px}.wf-editor select{height:38px;font-size:12px}.wf-type{display:grid;grid-template-columns:repeat(3,1fr);gap:5px}.wf-type button{height:34px;border:1px solid #d7e0ea;background:#fff;border-radius:8px;font-size:10px;font-weight:700;cursor:pointer}.wf-type button.active{border-color:#16c3c5;background:#e8fbfb;color:#087e80}.wf-save-row{display:flex;justify-content:flex-end}.wf-pill{font-size:10px;font-weight:800;padding:3px 6px;border-radius:999px;background:#f1f5f9;color:#607087}@media(max-width:760px){.wf-grid{grid-template-columns:repeat(7,minmax(250px,1fr))}.wf-week-title{font-size:16px}}`;document.head.appendChild(s);}
async function load(){
const {data:u,error:ue}=await sb.auth.getUser();if(ue)throw ue;if(!u.user)throw new Error('Chưa đăng nhập.');
const {data:p,error:pe}=await sb.from('profiles').select('id,full_name,role,status,access_scope').eq('id',u.user.id).single();
if(pe)throw pe;if(String(p.status).toUpperCase()!=='ACTIVE')throw new Error('Tài khoản chưa ở trạng thái ACTIVE.');
profileRole=String(p.role||'STAFF').toUpperCase();
const weekKey=key(week);
const scheduleCall=['OWNER','STORE_MANAGER'].includes(profileRole)
?sb.rpc('get_manager_weekly_schedule',{p_store_id:null,p_week_start:weekKey})
:sb.rpc('list_my_approved_schedules_v2',{p_week_start:weekKey});
const [{data:a,error:ae},{data:s,error:se},{data:st,error:ste}]=await Promise.all([
sb.rpc('get_my_availability',{p_week_start:weekKey}),scheduleCall,sb.from('stores').select('id,code,name,status').eq('status','ACTIVE').order('name')]);
if(ae)throw ae;if(se)throw se;if(ste)throw ste;
availability=Array.isArray(a)?a:[];schedules=Array.isArray(s)?s.map(x=>({date:x.date||x.work_date,start:x.start||x.start_time,end:x.end||x.end_time,...x})):[];stores=Array.isArray(st)?st:[];}
function dayHtml(d,i){const k=key(d);const shifts=schedules.filter(x=>String(x.date).slice(0,10)===k&&String(x.status).toUpperCase()==='APPROVED');const av=availability.filter(x=>String(x.work_date).slice(0,10)===k);return `<article class="wf-day"><header class="wf-day-head"><strong>${DAYS[i]}</strong><span>${fmt(d)}</span></header><div class="wf-block"><div class="wf-block-title"><span>Lịch chính thức</span><span class="wf-pill">${shifts.length} ca</span></div>${shifts.length?shifts.map(x=>`<div class="wf-shift"><b>${esc(x.start)}–${esc(x.end)}</b><small>${esc(x.store_name||x.store_code||'Cửa hàng')}</small></div>`).join(''):'<div class="wf-empty">Chưa có ca được duyệt</div>'}</div><div class="wf-block"><div class="wf-block-title"><span>Khả năng làm</span><span class="wf-pill">${av.length} khoảng</span></div><div class="wf-list">${av.length?av.map(x=>`<div class="wf-item"><div><strong>${esc(String(x.start_time).slice(0,5))}–${esc(String(x.end_time).slice(0,5))}</strong><span>${esc(TYPES[String(x.availability_type).toUpperCase()]||x.availability_type)}${x.preferred_store_id?' · '+esc(stores.find(s=>String(s.id)===String(x.preferred_store_id))?.name||'Cửa hàng ưu tiên'):''}</span></div><button class="wf-mini" data-delete="${esc(x.id)}">Xóa</button></div>`).join(''):'<div class="wf-empty">Chưa khai báo</div>'}</div><div class="wf-editor" data-day="${k}"><div class="wf-editor-row"><select data-start>${timeOpts('')}</select><select data-end>${timeOpts('')}</select></div><div class="wf-type">${Object.keys(TYPES).map((t,j)=>`<button type="button" data-type="${t}" class="${j===0?'active':''}">${TYPES[t]}</button>`).join('')}</div><select data-store>${storeOpts('')}</select><div class="wf-save-row"><button type="button" class="wf-btn primary" data-save="${k}">Thêm khoảng</button></div></div></div></article>`;}
function render(){const box=$('content');if(!box)return;const end=add(week,6);if($('pageTitle'))$('pageTitle').textContent='Lịch làm';if($('pageDescription'))$('pageDescription').textContent='Lịch chính thức và khả năng làm việc';document.querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page==='schedule'));box.innerHTML=`<div class="wf-shell"><section class="card panel"><div class="wf-toolbar"><div><div class="wf-week-title">Tuần ${fmt(week)} – ${fmt(end)}</div><div class="wf-muted">Thứ Hai → Chủ Nhật · Asia/Ho_Chi_Minh</div></div><div class="wf-toolbar-group"><button class="wf-btn" id="wf-prev">← Tuần trước</button><button class="wf-btn" id="wf-now">Tuần này</button><button class="wf-btn" id="wf-next">Tuần sau →</button></div></div><div class="wf-status" id="wf-status"></div><p class="wf-note">Lịch chính thức chỉ hiển thị ca đã duyệt. Bạn có thể khai báo nhiều khoảng thời gian trong cùng ngày; “Không thể làm” được ưu tiên khi chồng lấn.</p></section><section class="wf-grid">${Array.from({length:7},(_,i)=>dayHtml(add(week,i),i)).join('')}</section></div>`;bind();}
function status(t,e=false){const x=$('wf-status');if(x){x.textContent=t||'';x.style.color=e?'#9d3f30':'#2d6b55';}}
function bind(){if($('wf-prev'))$('wf-prev').onclick=async()=>{week=add(week,-7);await refresh();};if($('wf-now'))$('wf-now').onclick=async()=>{week=monday(businessToday());await refresh();};if($('wf-next'))$('wf-next').onclick=async()=>{week=add(week,7);await refresh();};document.querySelectorAll('[data-type]').forEach(b=>b.onclick=()=>{const e=b.closest('.wf-editor');e.querySelectorAll('[data-type]').forEach(x=>x.classList.remove('active'));b.classList.add('active');});document.querySelectorAll('[data-save]').forEach(b=>b.onclick=()=>save(b.dataset.save,b));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>remove(b.dataset.delete,b));}
async function save(day,b){const e=document.querySelector(`[data-day="${day}"]`),start=e.querySelector('[data-start]').value,end=e.querySelector('[data-end]').value,type=e.querySelector('[data-type].active')?.dataset.type||'AVAILABLE',store=e.querySelector('[data-store]').value||null;if(!start||!end||mins(end)<=mins(start)){status('Khoảng thời gian không hợp lệ.',true);return;}b.disabled=true;try{const {error}=await sb.rpc('save_my_availability',{p_availability_id:null,p_work_date:day,p_start_time:start,p_end_time:end,p_availability_type:type,p_preferred_store_id:store,p_note:null});if(error)throw error;status('Đã lưu khoảng thời gian.');await refresh();}catch(err){status(err.message||'Không thể lưu.',true);}finally{b.disabled=false;}}
async function remove(id,b){if(!confirm('Xóa khoảng thời gian này?'))return;b.disabled=true;try{const {data,error}=await sb.rpc('delete_my_availability',{p_availability_id:id});if(error)throw error;if(!data)throw new Error('Không thể xóa khoảng thời gian.');status('Đã xóa.');await refresh();}catch(err){status(err.message||'Không thể xóa.',true);}finally{b.disabled=false;}}
async function refresh(){try{await load();render();}catch(err){const box=$('content');if(box)box.innerHTML=`<section class="card panel"><h2>Lịch làm</h2><div class="wf-error">${esc(err.message||'Không thể tải dữ liệu Workforce.')}</div></section>`;}}
function capture(e){if(!enabled)return;const b=e.target.closest('[data-page="schedule"]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();refresh();}
async function init(){styles();enabled=true;document.addEventListener('click',capture,true);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})(window,document);
